import type { TemplateContext } from '../../lib/types';

function lines(...content: string[]): string {
  return `${content.join('\n')}\n`;
}

export const GRAPHQL_GUARD_DEPENDENCIES = [
  '@apollo/server',
  '@as-integrations/fastify',
  '@nestjs/apollo',
  '@nestjs/graphql',
  'graphql',
] as const;

export const GRAPHQL_MANAGED_PATHS = ['src/modules/graphql'] as const;

export function buildGraphqlFeatureFiles(
  context: TemplateContext,
): Record<string, string> {
  return {
    'src/modules/graphql/index.ts': lines(
      "export { GraphqlFeatureModule } from './graphql.module';",
    ),
    'src/modules/graphql/graphql.module.ts': lines(
      "import { Module } from '@nestjs/common';",
      '',
      "import { AuthModule } from '../auth/auth.module';",
      "import { GraphqlDemoResolver } from './graphql-demo.resolver';",
      "import { GqlOptionalAuthGuard } from './security/gql-optional-auth.guard';",
      '',
      '@Module({',
      '  imports: [AuthModule],',
      '  providers: [GraphqlDemoResolver, GqlOptionalAuthGuard],',
      '})',
      'export class GraphqlFeatureModule {}',
    ),
    'src/modules/graphql/graphql-demo.type.ts': lines(
      "import { Field, ObjectType } from '@nestjs/graphql';",
      '',
      '@ObjectType()',
      'export class GraphqlDemo {',
      '  @Field(() => String)',
      '  service!: string;',
      '',
      '  @Field(() => Boolean)',
      '  authenticated!: boolean;',
      '',
      '  @Field(() => String, { nullable: true })',
      '  guestUserId!: string | null;',
      '}',
    ),
    'src/modules/graphql/graphql-demo.resolver.ts': lines(
      "import { UseGuards } from '@nestjs/common';",
      "import { Query, Resolver } from '@nestjs/graphql';",
      '',
      "import { GraphqlDemo } from './graphql-demo.type';",
      "import {",
      "  CurrentGraphqlUser,",
      "  type GraphqlCurrentUser,",
      "} from './security/current-graphql-user.decorator';",
      "import { GqlOptionalAuthGuard } from './security/gql-optional-auth.guard';",
      '',
      '@Resolver(() => GraphqlDemo)',
      'export class GraphqlDemoResolver {',
      "  @Query(() => GraphqlDemo, { name: 'graphqlDemo' })",
      '  @UseGuards(GqlOptionalAuthGuard)',
      '  getGraphqlDemo(',
      '    @CurrentGraphqlUser() currentUser: GraphqlCurrentUser,',
      '  ): GraphqlDemo {',
      '    return {',
      `      service: ${JSON.stringify(context.appName)},`,
      '      authenticated: Boolean(currentUser.user?.sub),',
      '      guestUserId: currentUser.guestUserId,',
      '    };',
      '  }',
      '}',
    ),
    'src/modules/graphql/security/current-graphql-user.decorator.ts': lines(
      "import { ExecutionContext, createParamDecorator } from '@nestjs/common';",
      "import { GqlExecutionContext } from '@nestjs/graphql';",
      '',
      'export interface GraphqlCurrentUser {',
      '  user: { sub?: string } | null;',
      '  guestUserId: string | null;',
      '}',
      '',
      'export const CurrentGraphqlUser = createParamDecorator(',
      '  (_data: unknown, context: ExecutionContext): GraphqlCurrentUser => {',
      '    const gqlContext = GqlExecutionContext.create(context).getContext<{',
      '      req?: { user?: { sub?: string } | null };',
      '      guestUserId?: string | null;',
      '    }>();',
      '',
      '    return {',
      '      user: gqlContext.req?.user ?? null,',
      '      guestUserId: gqlContext.guestUserId ?? null,',
      '    };',
      '  },',
      ');',
    ),
    'src/modules/graphql/security/gql-optional-auth.guard.ts': lines(
      "import { ExecutionContext, Injectable } from '@nestjs/common';",
      "import { GqlExecutionContext } from '@nestjs/graphql';",
      "import { AuthGuard } from '@nestjs/passport';",
      '',
      '@Injectable()',
      "export class GqlOptionalAuthGuard extends AuthGuard('jwt') {",
      '  canActivate(context: ExecutionContext) {',
      '    const request = this.getRequest(context);',
      '    const authorization =',
      '      request?.headers?.authorization ?? request?.headers?.Authorization;',
      '    const hasBearer =',
      "      typeof authorization === 'string' &&",
      "      authorization.toLowerCase().startsWith('bearer ');",
      '',
      '    if (!hasBearer) {',
      '      return true;',
      '    }',
      '',
      '    return super.canActivate(context);',
      '  }',
      '',
      '  getRequest(context: ExecutionContext) {',
      '    const gqlContext = GqlExecutionContext.create(context).getContext<{',
      '      req?: { headers?: Record<string, unknown> };',
      '    }>();',
      '',
      '    return gqlContext.req;',
      '  }',
      '',
      '  handleRequest(err: unknown, user: unknown) {',
      '    if (err || !user) {',
      '      return null;',
      '    }',
      '',
      '    return user;',
      '  }',
      '}',
    ),
  };
}

export const QUEUE_GUARD_DEPENDENCIES = ['@nestjs/bullmq', 'bullmq'] as const;

export const QUEUE_MANAGED_PATHS = ['src/modules/queue'] as const;

export function buildQueueFeatureFiles(): Record<string, string> {
  return {
    'src/modules/queue/index.ts': lines(
      "export { QueueFeatureModule } from './queue.module';",
    ),
    'src/modules/queue/queue.constants.ts': lines(
      "export const DEMO_QUEUE_NAME = 'demo-queue';",
      "export const DEMO_JOB_NAME = 'queue.demo';",
    ),
    'src/modules/queue/queue.schemas.ts': lines(
      "import { z } from 'zod';",
      '',
      'export const QueueDemoRequestSchema = z.object({',
      '  message: z.string().trim().min(1),',
      '});',
      '',
      'export type QueueDemoRequest = z.infer<typeof QueueDemoRequestSchema>;',
    ),
    'src/modules/queue/queue.service.ts': lines(
      "import { InjectQueue } from '@nestjs/bullmq';",
      "import { Injectable } from '@nestjs/common';",
      "import { Queue } from 'bullmq';",
      '',
      "import { DEMO_JOB_NAME, DEMO_QUEUE_NAME } from './queue.constants';",
      "import type { QueueDemoRequest } from './queue.schemas';",
      '',
      '@Injectable()',
      'export class QueueProducerService {',
      '  constructor(',
      '    @InjectQueue(DEMO_QUEUE_NAME) private readonly demoQueue: Queue,',
      '  ) {}',
      '',
      '  async enqueueDemoJob(input: QueueDemoRequest) {',
      '    const job = await this.demoQueue.add(DEMO_JOB_NAME, {',
      '      message: input.message,',
      '    });',
      '',
      '    return {',
      "      jobId: job.id ? String(job.id) : null,",
      '      queue: DEMO_QUEUE_NAME,',
      '      name: DEMO_JOB_NAME,',
      '      message: input.message,',
      '    };',
      '  }',
      '}',
    ),
    'src/modules/queue/queue.controller.ts': lines(
      "import { Body, Controller, Post } from '@nestjs/common';",
      '',
      "import { QueueDemoRequestSchema } from './queue.schemas';",
      "import { QueueProducerService } from './queue.service';",
      '',
      "@Controller('queue')",
      'export class QueueController {',
      '  constructor(',
      '    private readonly queueProducer: QueueProducerService,',
      '  ) {}',
      '',
      "  @Post('demo')",
      '  async enqueueDemo(@Body() body: unknown) {',
      '    const request = QueueDemoRequestSchema.parse(body);',
      '',
      '    return this.queueProducer.enqueueDemoJob(request);',
      '  }',
      '}',
    ),
    'src/modules/queue/queue.module.ts': lines(
      "import { BullModule } from '@nestjs/bullmq';",
      "import { Module } from '@nestjs/common';",
      '',
      "import { DEMO_QUEUE_NAME } from './queue.constants';",
      "import { QueueController } from './queue.controller';",
      "import { QueueProducerService } from './queue.service';",
      '',
      '@Module({',
      '  imports: [',
      '    BullModule.registerQueue({',
      '      name: DEMO_QUEUE_NAME,',
      '      defaultJobOptions: {',
      '        attempts: 3,',
      '        removeOnComplete: true,',
      '        removeOnFail: 20,',
      '      },',
      '    }),',
      '  ],',
      '  controllers: [QueueController],',
      '  providers: [QueueProducerService],',
      '  exports: [QueueProducerService],',
      '})',
      'export class QueueFeatureModule {}',
    ),
  };
}

export const CACHE_GUARD_DEPENDENCIES = [
  '@keyv/redis',
  '@nestjs/cache-manager',
  'cache-manager',
] as const;

export const CACHE_MANAGED_PATHS = ['src/modules/cache'] as const;

export function buildCacheFeatureFiles(): Record<string, string> {
  return {
    'src/modules/cache/index.ts': lines(
      "export { CacheFeatureModule } from './cache.module';",
      "export { CacheDemoService } from './cache.service';",
    ),
    'src/modules/cache/cache.schemas.ts': lines(
      "import { z } from 'zod';",
      '',
      'export const CacheDemoKeySchema = z.string().trim().min(1);',
      '',
      'export const CacheDemoRequestSchema = z.object({',
      '  key: CacheDemoKeySchema,',
      '  value: z.string().trim().min(1),',
      '  ttlMs: z.coerce.number().int().positive().max(86_400_000).optional(),',
      '});',
      '',
      'export type CacheDemoRequest = z.infer<typeof CacheDemoRequestSchema>;',
    ),
    'src/modules/cache/cache.service.ts': lines(
      "import { CACHE_MANAGER } from '@nestjs/cache-manager';",
      "import { Inject, Injectable } from '@nestjs/common';",
      "import type { Cache } from 'cache-manager';",
      '',
      "import type { CacheDemoRequest } from './cache.schemas';",
      '',
      '@Injectable()',
      'export class CacheDemoService {',
      '  constructor(@Inject(CACHE_MANAGER) private readonly cacheManager: Cache) {}',
      '',
      '  async setValue(request: CacheDemoRequest) {',
      '    const ttlMs = request.ttlMs ?? 60_000;',
      '',
      '    await this.cacheManager.set(request.key, request.value, ttlMs);',
      '',
      '    return {',
      '      key: request.key,',
      '      value: request.value,',
      '      ttlMs,',
      '    };',
      '  }',
      '',
      '  async getValue(key: string) {',
      '    return {',
      '      key,',
      '      value: (await this.cacheManager.get<string>(key)) ?? null,',
      '    };',
      '  }',
      '}',
    ),
    'src/modules/cache/cache.controller.ts': lines(
      "import { Body, Controller, Get, Param, Post } from '@nestjs/common';",
      '',
      "import {",
      "  CacheDemoKeySchema,",
      "  CacheDemoRequestSchema,",
      "} from './cache.schemas';",
      "import { CacheDemoService } from './cache.service';",
      '',
      "@Controller('cache')",
      'export class CacheController {',
      '  constructor(private readonly cacheDemo: CacheDemoService) {}',
      '',
      "  @Post('demo')",
      "  async setDemoValue(@Body() body: unknown) {",
      '    const request = CacheDemoRequestSchema.parse(body);',
      '',
      '    return this.cacheDemo.setValue(request);',
      '  }',
      '',
      "  @Get('demo/:key')",
      '  async getDemoValue(@Param(\'key\') key: string) {',
      '    const parsedKey = CacheDemoKeySchema.parse(key);',
      '',
      '    return this.cacheDemo.getValue(parsedKey);',
      '  }',
      '}',
    ),
    'src/modules/cache/cache.module.ts': lines(
      "import { Module } from '@nestjs/common';",
      '',
      "import { CacheController } from './cache.controller';",
      "import { CacheDemoService } from './cache.service';",
      '',
      '@Module({',
      '  controllers: [CacheController],',
      '  providers: [CacheDemoService],',
      '  exports: [CacheDemoService],',
      '})',
      'export class CacheFeatureModule {}',
    ),
  };
}

export const LLM_GUARD_DEPENDENCIES = ['openai'] as const;

export const LLM_MANAGED_PATHS = ['src/modules/llm'] as const;

export function buildLlmFeatureFiles(): Record<string, string> {
  return {
    'src/modules/llm/index.ts': lines(
      "export { LlmFeatureModule } from './llm.module';",
    ),
    'src/modules/llm/llm.schemas.ts': lines(
      "import { z } from 'zod';",
      '',
      'export const LlmDemoRequestSchema = z.object({',
      '  prompt: z.string().trim().min(1),',
      "  provider: z.enum(['openai']).default('openai'),",
      '});',
      '',
      'export type LlmDemoRequest = z.infer<typeof LlmDemoRequestSchema>;',
    ),
    'src/modules/llm/openai.provider.ts': lines(
      "import OpenAI from 'openai';",
      '',
      "import type { Config } from '../../types/config';",
      "import { Service } from '../tokens';",
      '',
      "export const OPENAI_CLIENT = Symbol('OPENAI_CLIENT');",
      '',
      'export const openAiClientProvider = {',
      '  provide: OPENAI_CLIENT,',
      '  inject: [Service.CONFIG],',
      '  useFactory: (config: Config): OpenAI =>',
      '    new OpenAI({',
      '      apiKey: config.OPENAI_API_KEY,',
      '    }),',
      '};',
    ),
    'src/modules/llm/llm.service.ts': lines(
      "import { Inject, Injectable } from '@nestjs/common';",
      "import OpenAI from 'openai';",
      '',
      "import type { Config } from '../../types/config';",
      "import { Service } from '../tokens';",
      "import type { LlmDemoRequest } from './llm.schemas';",
      "import { OPENAI_CLIENT } from './openai.provider';",
      '',
      '@Injectable()',
      'export class LlmService {',
      '  constructor(',
      '    @Inject(OPENAI_CLIENT) private readonly openAi: OpenAI,',
      '    @Inject(Service.CONFIG) private readonly config: Config,',
      '  ) {}',
      '',
      '  async runPromptChain(request: LlmDemoRequest) {',
      '    const completion = await this.openAi.chat.completions.create({',
      '      model: this.config.OPENAI_MODEL,',
      '      temperature: 0,',
      '      messages: [',
      '        {',
      "          role: 'system',",
      "          content: 'You are the concise LLM demo for a generated NestJS server.',",
      '        },',
      '        {',
      "          role: 'user',",
      '          content:',
      "            `Summarize the intent of the following prompt in one short paragraph.\\n\\n${request.prompt}`,",
      '        },',
      '      ],',
      '    });',
      '',
      '    const output =',
      '      completion.choices.find(',
      '        (choice) =>',
      "          typeof choice.message.content === 'string' &&",
      '          choice.message.content.trim().length > 0,',
      '      )?.message.content?.trim() ?? \'\';',
      '',
      '    return {',
      '      provider: request.provider,',
      '      model: this.config.OPENAI_MODEL,',
      '      output,',
      '    };',
      '  }',
      '}',
    ),
    'src/modules/llm/llm.controller.ts': lines(
      "import { Body, Controller, Post } from '@nestjs/common';",
      '',
      "import { LlmDemoRequestSchema } from './llm.schemas';",
      "import { LlmService } from './llm.service';",
      '',
      "@Controller('llm')",
      'export class LlmController {',
      '  constructor(private readonly llm: LlmService) {}',
      '',
      "  @Post('demo')",
      '  async runDemo(@Body() body: unknown) {',
      '    const request = LlmDemoRequestSchema.parse(body);',
      '',
      '    return this.llm.runPromptChain(request);',
      '  }',
      '}',
    ),
    'src/modules/llm/llm.module.ts': lines(
      "import { Module } from '@nestjs/common';",
      '',
      "import { CommonModule } from '../common';",
      "import { LlmController } from './llm.controller';",
      "import { LlmService } from './llm.service';",
      "import { openAiClientProvider } from './openai.provider';",
      '',
      '@Module({',
      '  imports: [CommonModule],',
      '  controllers: [LlmController],',
      '  providers: [openAiClientProvider, LlmService],',
      '  exports: [LlmService],',
      '})',
      'export class LlmFeatureModule {}',
    ),
  };
}
